import java.io.File

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

val certsDir = rootProject.file("certs")

// Register generated directories as source set inputs
val generatedCertRes = layout.buildDirectory.dir("generated/res/cert-res")
val generatedNscRes = layout.buildDirectory.dir("generated/res/cert-nsc")
val generatedCertKt = layout.buildDirectory.dir("generated/source/cert-ids/kotlin")

android {
    namespace = "io.github.iharee.webrtcp2pliveandroid"
    compileSdk = 36

    defaultConfig {
        applicationId = "io.github.iharee.webrtcp2pliveandroid"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }

    sourceSets {
        named("main") {
            res.srcDir(generatedCertRes)
            res.srcDir(generatedNscRes)
            kotlin.srcDir(generatedCertKt)
        }
    }
}

// Process certs/ at build time: copy certs into raw resources,
// generate network_security_config.xml, and generate CertResources.kt
tasks.register("processCerts") {
    group = "build"
    description = "Scans certs/*.pem and generates cert resources + network security config"

    inputs.dir(certsDir)
    val rawOutDir = generatedCertRes.map { it.dir("raw") }
    val nscOutFile = generatedNscRes.map { it.file("xml/network_security_config.xml") }
    val ktOutFile = generatedCertKt.map { it.file("io/github/iharee/webrtcp2pliveandroid/CertResources.kt") }
    outputs.dir(rawOutDir)
    outputs.file(nscOutFile)
    outputs.file(ktOutFile)

    doLast {
        val certFiles = certsDir.takeIf { it.isDirectory }
            ?.listFiles { f -> f.extension.equals("pem", ignoreCase = true) }
            ?: emptyArray()

        // Sanitize filename to a valid Android resource name: lowercase, [a-z0-9_]
        fun resName(f: File): String =
            f.nameWithoutExtension.lowercase().replace(Regex("[^a-z0-9_]"), "_")

        // 1) Copy cert files into raw resource directory
        val rawDir = rawOutDir.get().asFile.apply { deleteRecursively(); mkdirs() }
        for (cert in certFiles) {
            cert.copyTo(File(rawDir, cert.name), overwrite = true)
        }

        // 2) Generate network_security_config.xml
        val nscFile = nscOutFile.get().asFile.apply { parentFile.mkdirs() }
        val xml = buildString {
            appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
            appendLine("<network-security-config>")
            appendLine("    <base-config>")
            appendLine("        <trust-anchors>")
            appendLine("            <certificates src=\"system\" />")
            for (cert in certFiles) {
                appendLine("            <certificates src=\"@raw/${resName(cert)}\" />")
            }
            appendLine("        </trust-anchors>")
            appendLine("    </base-config>")
            appendLine("</network-security-config>")
        }
        nscFile.writeText(xml)

        // 3) Generate CertResources.kt
        val ktFile = ktOutFile.get().asFile.apply { parentFile.mkdirs() }
        val kt = buildString {
            appendLine("package io.github.iharee.webrtcp2pliveandroid")
            appendLine()
            appendLine("// Auto-generated by processCerts Gradle task — lists all certificate resource names found in certs/")
            appendLine("object CertResources {")
            append("    val names: List<String> = ")
            if (certFiles.isEmpty()) {
                appendLine("emptyList()")
            } else {
                appendLine("listOf(")
                for ((i, cert) in certFiles.withIndex()) {
                    val comma = if (i < certFiles.size - 1) "," else ""
                    appendLine("        \"${resName(cert)}\"$comma")
                }
                appendLine("    )")
            }
            appendLine("}")
        }
        ktFile.writeText(kt)
    }
}

// Run processCerts before every build
tasks.named("preBuild") { dependsOn("processCerts") }

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.okhttp)
    implementation(libs.gson)
    implementation(libs.stream.webrtc.android)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}